/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 0.99.3. DO NOT MODIFY.
*/
module topEntity
    ( // Inputs
      input  clk // clock
    , input  rst // asynchronous reset: active high
    , input [16:0] driverOut 
    , input  sensorOut 

      // Outputs
    , output wire [1:0] sensorIn 
    , output wire [16:0] driverIn 
    , output wire [1:0] clkOut // gated clock
    );
  wire [1:0] \#app_arg ;
  wire [16:0] x;
  wire  x_0;
  wire  x_1;
  wire [19:0] tup;
  wire  x_2;
  wire [2:0] x_3;
  wire [17:0] spiIn;
  wire [19:0] res;

  assign spiIn = {driverOut,sensorOut};

  assign res = {{x_0,x_1},x,\#app_arg };

  // clockGate begin 
  assign \#app_arg  = {clk,((x_2) == 1'b1)};
  // clockGate end

  assign x = tup[16:0];

  assign x_0 = x_3[1:1];

  assign x_1 = x_3[0:0];

  Modules_Interfaces_SPI_CtrlSim_main2 Modules_Interfaces_SPI_CtrlSim_main2_tup
    ( .result (tup)
    , .clk (clk)
    , .rst (rst)
    , .\input  (spiIn) );

  assign x_2 = x_3[2:2];

  assign x_3 = tup[19:17];

  assign sensorIn = res[19:18];

  assign driverIn = res[17:1];

  assign clkOut = res[0:0];
endmodule

