/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 0.99.1. DO NOT MODIFY.
*/
module LightSensor_I_interface_sinterface
    ( // Inputs
      input  clk // clock
    , input  rst // asynchronous reset: active high
    , input [9:0] i1 

      // Outputs
    , output wire [17:0] y 
    );
  reg [7:0] \#tup_case_alt ;
  wire [7:0] ds1;
  reg [7:0] state;
  wire  ds2;
  wire  \#tup_case_alt_selection_res ;

  assign y = {state,{8'b00000000,1'b0,1'b0}};

  assign \#tup_case_alt_selection_res  = ds2 == (1'b1);

  always @(*) begin
    if(\#tup_case_alt_selection_res )
      \#tup_case_alt  = ds1;
    else
      \#tup_case_alt  = state;
  end

  assign ds1 = i1[9:2];

  // register begin
  always @(posedge clk or posedge rst) begin : LightSensor_I_interface_sinterface_register
    if (rst) begin
      state <= 8'b00000000;
    end else begin
      state <= \#tup_case_alt ;
    end
  end
  // register end

  assign ds2 = i1[1:1];
endmodule

