/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 0.99.1. DO NOT MODIFY.
*/
module LightSensor_spi_Ctrl
    ( // Inputs
      input  clk // clock
    , input  rst // asynchronous reset: active high
    , input [10:0] \input  

      // Outputs
    , output wire [12:0] result 
    );
  wire [1:0] \#app_arg ;
  wire [9:0] y;
  wire  x;
  wire  x_0;
  wire [12:0] tup;
  wire  x_1;
  wire [2:0] x_2;

  assign result = {{x,x_0},y,\#app_arg };

  // clockGate begin 
  assign \#app_arg  = {clk,((x_1) == 1'b1)};
  // clockGate end

  assign y = tup[9:0];

  assign x = x_2[1:1];

  assign x_0 = x_2[0:0];

  LightSensor_spiCtrl LightSensor_spiCtrl_tup
    ( .y (tup)
    , .eta (clk)
    , .eta_0 (rst)
    , .eta_1 (\input ) );

  assign x_1 = x_2[2:2];

  assign x_2 = tup[12:10];
endmodule

